//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uhanov.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Book()
        {
            this.BookAreaOfKnowledge = new HashSet<BookAreaOfKnowledge>();
            this.BookAuthor1 = new HashSet<BookAuthor>();
        }
    
        public int IdBook { get; set; }
        public string NameBook { get; set; }
        public int IdBookAuthor { get; set; }
        public int IdCity { get; set; }
        public int IdPublishingHouse { get; set; }
        public System.DateTime DateOfPublishing { get; set; }
        public decimal AmountOfPages { get; set; }
        public decimal Price { get; set; }
        public int CountInstance { get; set; }
    
        public virtual BookAuthor BookAuthor { get; set; }
        public virtual City City { get; set; }
        public virtual PublishingHouse PublishingHouse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookAreaOfKnowledge> BookAreaOfKnowledge { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookAuthor> BookAuthor1 { get; set; }
    }
}
