//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uhanov.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsageBooks
    {
        public int IdUsageBooksId { get; set; }
        public int IdReader { get; set; }
        public System.DateTime DateOfIssue { get; set; }
        public System.DateTime DateOfDue { get; set; }
        public int IdInstance { get; set; }
    
        public virtual Instance Instance { get; set; }
        public virtual Reader Reader { get; set; }
    }
}
